#!/bin/python3

import math
import os
import random
import re
import sys


#
# Complete the 'diagonalDifference' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY arr as parameter.
#

def diagonalDifference(ar):
    sum1=0
    sum2=0
    length = len(ar[0])
    for i in range(length):
        sum1 += ar[i][i]
        sum2 += ar[i][length-i-1]
    return (abs(sum1-sum2))
    
 
   
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    ar = []

    for _ in range(n):
        ar.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(ar)

    fptr.write(str(result) + '\n')

    fptr.close()
